### ISSUE TITLE
Compose JS (WebAssembly) Class Not Found exception

### ISSUE THREAD

**Issue by DjakaTechnology** [russhwolf/multiplatform-settings#129]
Got runtime crash on web assembly caused by coroutines.

You can repro it using this branch: https://github.com/DjakaTechnology/droidjam-managing-state-compose/pull/3
```
"ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:27343:11)
    at new PreferenceRepository (webpack-internal:///./kotlin/droidjam-core.js:486:70)
    at eval (webpack-internal:///./kotlin/droidjam-core.js:374:14)
    at UnsafeLazyImpl.get_value_j01efc_k$ (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:12875:56)
    at CoreComponent.get_preferenceRepository_az2766_k$ (webpack-internal:///./kotlin/droidjam-core.js:426:56)
    at new LocaleSubComponent (webpack-internal:///./kotlin/droidjam-locale-app.js:262:59)
    at LocaleDIManager.subComponent_bhytgd_k$ (webpack-internal:///./kotlin/droidjam-locale-app.js:206:12)
    at LocalePresenterProviderImpl.provideCountryPickerPresenter_t8zm85_k$ (webpack-internal:///./kotlin/droidjam-locale-app.js:351:44)
    at createPresenter (webpack-internal:///./kotlin/droidjam-locale-ui.js:2215:91)
    at CountryPickerScreen$composable_0 (webpack-internal:///./kotlin/droidjam-locale-ui.js:2066:31)"
````

**Comment by russhwolf** [comment]
Can you put together a more minimal sample? That's a 3000 line PR with a lot of different things going on, and it's not at all clear to me whether your issue is related to Multiplatform Settings or not.
