### ISSUE TITLE
KeyStore error

### ISSUE THREAD

**Issue by charlee-dev** [russhwolf/multiplatform-settings#141]
Hi. We get an error while getting encrypted settings. It always fails on a fresh install when it tries to decrypt a key from Keystore. Clearing app data fixes the issue.  I can reproduce it on Pixel 4 XL on Android 13. A bit weird because I can not reproduce it on every Android 13 device.

multiplafrorm-settings = v1.0.0

This is how we create SharedPreferencesSettings on Android:
```kotlin
SharedPreferencesSettings(
            delegate = EncryptedSharedPreferences.create(
                get(),
                secureSettingsFilename,
                MasterKey.Builder(get())
                    .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
                    .build(),
                EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
            )
        )
```

And the stack trace:
```kotlin
Caused by:
                     0: In finish: KeyMint::finish failed.
                     1: Error::Km(ErrorCode(-30))) (public error code: 10 internal Keystore code: -30)
                 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
                 	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
                 	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
14:13:14.505  W  	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
                 	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
                 	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
                 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
                 	... 91 more
14:13:14.524  W  cannot decrypt keyset: 
                 javax.crypto.AEADBadTagException
                 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:611)
                 	at javax.crypto.Cipher.doFinal(Cipher.java:2114)
                 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115)
                 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
                 	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:845)
                 	at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:732)
                 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:713)
                 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:315)
                 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:288)
                 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:239)
                 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:165)
                 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:130)
                 	at com.txconnected.mobox.di.KoinAndroidKt$platformModule$1$2.invoke(KoinAndroid.kt:40)
                 	at com.txconnected.mobox.di.KoinAndroidKt$platformModule$1$2.invoke(KoinAndroid.kt:38)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
                 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
                 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
                 	at org.koin.core.scope.Scope.get(Scope.kt:205)
                 	at com.txconnected.mobox.di.modules.UserModuleKt$userModule$1$3.invoke(UserModule.kt:60)
                 	at com.txconnected.mobox.di.modules.UserModuleKt$userModule$1$3.invoke(UserModule.kt:33)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
                 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
                 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
                 	at org.koin.core.scope.Scope.get(Scope.kt:205)
                 	at com.txconnected.mobox.di.modules.DatabaseModuleKt$databaseModuleCommon$1$10.invoke(DatabaseModule.kt:126)
                 	at com.txconnected.mobox.di.modules.DatabaseModuleKt$databaseModuleCommon$1$10.invoke(DatabaseModule.kt:89)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
                 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
14:13:14.525  W  	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
                 	at org.koin.core.scope.Scope.get(Scope.kt:205)
                 	at com.txconnected.mobox.di.modules.TripModuleKt$tripModule$1$2.invoke(TripModule.kt:134)
                 	at com.txconnected.mobox.di.modules.TripModuleKt$tripModule$1$2.invoke(TripModule.kt:33)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
                 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
                 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
                 	at org.koin.core.scope.Scope.get(Scope.kt:205)
                 	at com.txconnected.mobox.di.modules.TripModuleKt$tripModule$1$7.invoke(TripModule.kt:129)
                 	at com.txconnected.mobox.di.modules.TripModuleKt$tripModule$1$7.invoke(TripModule.kt:81)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
                 	at org.koin.core.registry.InstanceRegistry.createEagerInstances(InstanceRegistry.kt:91)
                 	at org.koin.core.registry.InstanceRegistry.createAllEagerInstances$koin_core(InstanceRegistry.kt:54)
                 	at org.koin.core.Koin.createEagerInstances(Koin.kt:348)
                 	at org.koin.core.KoinApplication.createEagerInstances(KoinApplication.kt:74)
                 	at com.txconnected.mobox.di.KoinKt$initSDKKoin$2.invoke(Koin.kt:77)
                 	at com.txconnected.mobox.di.KoinKt$initSDKKoin$2.invoke(Koin.kt:61)
                 	at org.koin.dsl.KoinApplicationKt.koinApplication(KoinApplication.kt:28)
                 	at com.txconnected.mobox.di.KoinKt.initSDKKoin(Koin.kt:61)
                 	at com.txconnected.mobox.android.SDKProvider.onCreate(SDKProvider.kt:25)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
                 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
                 	at com.txconnected.mobox.android.SDKProvider.attachInfo(SDKProvider.kt:42)
                 	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
                 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
                 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7898)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                 Caused by: android.security.KeyStoreException: Signature/MAC verification failed (internal Keystore code: -30 message: In KeystoreOperation::finish
                 
                 Caused by:
                     0: In finish: KeyMint::finish failed.
                     1: Error::Km(ErrorCode(-30))) (public error code: 10 internal Keystore code: -30)
                 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:369)
                 	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
                 	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
14:13:14.525  W  	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
                 	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
                 	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
                 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
                 	... 91 more
```

**Comment by russhwolf** [comment]
This seems more likely to be an EncryptedSharedPreferences issue than a Multiplatform Settings issue.

**Comment by darvelo** [comment]
I have the same problem when a test user uninstalled then reinstalled the app. It seems it could be any of these issues: https://stackoverflow.com/questions/55665337/keystoreexception-signature-mac-verification-failed-when-trying-to-decrypt

The top answer there is that the default on Android is [android:allowBackup="true"](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup), and the encryption keys in the keystore are not part of the backup, so when the preferences are restored without the keys, all encrypt/decrypt operations fail. I'm going to try setting `android:allowBackup="false"` and see if that fixes it.
