### ISSUE TITLE
ClassNotFoundException on JVM after updating Android Studio

### ISSUE THREAD

**Issue by GuilhE** [russhwolf/multiplatform-settings#168]
When running on JVM (Desktop app with compose multiplatform) I get this error:

```
actual class PlatformDependencies actual constructor() {
    actual fun getSettings(): Settings = PreferencesSettings.Factory().create("settings")
}
```

```
Caused by: java.lang.ClassNotFoundException: com.russhwolf.settings.Settings
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 50 more
```

Android and iOS both work fine.  
I've updated Android Studio from `Giraffe` to `Hedgehog` and Android Gradle Tools from `8.1.0` to `8.1.1`.

It doesn't makes sense 😓

**Comment by russhwolf** [comment]
Can you share a project that reproduces this? It's really hard to guess what's happening just from what you've shown here.

**Comment by GuilhE** [comment]
Yes of course, here it is: https://github.com/GuilhE/Expressus

**Comment by GuilhE** [comment]
Super strange behaviour, so if I run the app by: `./gradlew :desktopApp:run` (Gradle run configuration) it works with no problems.
If I use a Kotlin run configuration (automatically created if I press the green run icon in my Main.class), it fails 🤷🏼

**Comment by russhwolf** [comment]
I don't think I was ever able to reproduce this. Can you take a look again with version 1.1.0? Maybe building against newer Kotlin and AGP helps.

**Comment by GuilhE** [comment]
Still happening 😞 

```
Android Studio: Hedgehog | 2023.1.1 Beta 6
AGP: 8.1.2
Kotlin: 1.9.10
```

Have you tried my sample?

**Comment by josegbel** [comment]
@GuilhE I was encountering a very similar crash stacktrace and fixed it downgrading gradle wrapper to 7.6 and therefore target and compile using java 11.
(distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip) 

I can see on your project you are using 8.2. See if downgrading gradle is something you can do without too much hassle.

**Comment by tekinalper** [comment]
Looks like I'm having the same issue when I try to build a release variant of a RN bridge SDK integrated RN app. For native Android, I don't have any problem. Somehow gradle, java or AGP versions doesn't match I guess. I'm stuck, any suggestions without downgrading versions? :/

 ```
 FATAL EXCEPTION: main
                 Process: com.example, PID: 30834
                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/russhwolf/settings/SharedPreferencesSettings;
                 	at ...shared.KoinAndroidKt$platformModule$1$1.invoke(KoinAndroid.kt:12)
                 	at ....shared.KoinAndroidKt$platformModule$1$1.invoke(KoinAndroid.kt:11)
                 	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
                 	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
                 	at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
                 	at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
                 	at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
                 	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
                 	at org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
                 	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
                 	at org.koin.core.scope.Scope.get(Scope.kt:212)
                 	at ....shared...$special$$inlined$inject$default$1.invoke(KoinComponent.kt:67)
                 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                 	...
                 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
                 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
                 	at ..x.invokeSuspend(SourceFile:29)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8180)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6156409, Dispatchers.Main.immediate]
                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.russhwolf.settings.SharedPreferencesSettings" on path: DexPathList[[zip file
                 "/data/app/~~ypdeJJIPx62ouu32Mhd2GQ==/com.example-8IkbDphb4oekp3gczIT5qw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ypdeJJIPx62ouu32Mhd2GQ==/com.example-8IkbDphb4oekp3gczIT5qw==/lib/x86_64, /data/app/~~ypdeJJIPx62ouu32Mhd2GQ==/com.example-8IkbDphb4oekp3gczIT5qw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                 	... 34 more
```

**Comment by russhwolf** [comment]
@GuilhE I hadn't been able to get your project syncing last time I looked so I wasn't able to verify the issue. Today I was able to get it imported and reproduce it. One thing I found was that if I comment out the common module, I see the same error come up for a different dependency. 

```
Exception in thread "main" java.lang.NoClassDefFoundError: dev/icerock/moko/mvvm/internal/CreateViewModelScopeKt
	at dev.icerock.moko.mvvm.viewmodel.ViewModel.<init>(ViewModel.kt:13)
	at com.expressus.domain.viewModels.ExpressusViewModel.<init>(ExpressusViewModel.kt:14)
	at com.expressus.domain.DependencyInjectionKt$platformModule$1$1.invoke(DependencyInjection.kt:9)
	at com.expressus.domain.DependencyInjectionKt$platformModule$1$1.invoke(DependencyInjection.kt:9)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
	at org.koin.core.scope.Scope.get(Scope.kt:212)
	at com.expressus.domain.ViewModels.expressusStateViewModel(DependencyInjection.kt:21)
	at presentation.ComposableSingletons$ExpressusKt$lambda-1$1.invoke(Expressus.kt:26)
	at presentation.ComposableSingletons$ExpressusKt$lambda-1$1.invoke(Expressus.kt:23)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:115)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:114)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:227)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:226)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:221)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:219)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:39)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3341)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3274)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1013)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: dev.icerock.moko.mvvm.internal.CreateViewModelScopeKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 50 more
```

This, and the fact that it works fine if you run the correct gradle task, suggests to me that it's not an issue specific to Multiplatform Settings. I suspect it's actually an IDE issue with the way it sets up that run configuration.

**Comment by GuilhE** [comment]
@russhwolf thanks for your feedback! I'll open an issue on Google Issue Tracker and see how it goes.

**Comment by GuilhE** [comment]
It was assigned 😃 https://issuetracker.google.com/issues/305466098 I believe this concludes our findings, thanks for you help.
