### ISSUE TITLE
Update for Kotlin 1.3.30

### ISSUE THREAD

**Issue by DennisLits** [russhwolf/multiplatform-settings#23]
Fixed with #24 

After upgrading my project to Kotlin 1.3.30 this project stopped working when specifing an iOS target, on my windows machine only targeting android/jvm it works fine but loading the same project with implementation "com.russhwolf:multiplatform-settings:0.2" in the common source gives me the following error when I try to build on mac with an iOS target

```skipping /Users/dennis/.gradle/caches/modules-2/files-2.1/com.russhwolf/multiplatform-settings-iossim/0.2/3dbabaf50b3d510a2891cd049928467ff9ef4fd7/multiplatform-settings.klib. The abi versions don't match. Expected '[8]', found '5'
The compiler versions don't match either. Expected '[1.2]', found '1.1.1-release-6082'
Compilation failed: Could not find "/Users/dennis/.gradle/caches/modules-2/files-2.1/com.russhwolf/multiplatform-settings-iossim/0.2/3dbabaf50b3d510a2891cd049928467ff9ef4fd7/multiplatform-settings.klib" in [/Users/dennis/kotlinmultitest/sharedCode, /Users/dennis/.konan/klib, /Users/dennis/.konan/kotlin-native-macos-1.2/klib/common, /Users/dennis/.konan/kotlin-native-macos-1.2/klib/platform/ios_x64].
 
 * Source files: /* !Omitted list of every kotlin file! */
 * Compiler version info: Konan: 1.2 / Kotlin: 1.3.30
 * Output kind: FRAMEWORK
 
java.lang.IllegalStateException: Could not find "/Users/dennis/.gradle/caches/modules-2/files-2.1/com.russhwolf/multiplatform-settings-iossim/0.2/3dbabaf50b3d510a2891cd049928467ff9ef4fd7/multiplatform-settings.klib" in [/Users/dennis/kotlinmultitest/sharedCode, /Users/dennis/.konan/klib, /Users/dennis/.konan/kotlin-native-macos-1.2/klib/common, /Users/dennis/.konan/kotlin-native-macos-1.2/klib/platform/ios_x64].
    at org.jetbrains.kotlin.konan.library.KonanLibraryProperResolver.resolve(SearchPathResolver.kt:194)
    at org.jetbrains.kotlin.konan.library.SearchPathResolver$DefaultImpls.resolve$default(SearchPathResolver.kt:18)
    at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$findLibraries$userProvidedLibraries$1.invoke(KonanLibraryResolverImpl.kt:49)
    at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl$findLibraries$userProvidedLibraries$1.invoke(KonanLibraryResolverImpl.kt:24)
    at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
    at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702)
    at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:732)
    at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:723)
    at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.findLibraries(KonanLibraryResolverImpl.kt:50)
    at org.jetbrains.kotlin.konan.library.resolver.impl.KonanLibraryResolverImpl.resolveWithDependencies(KonanLibraryResolverImpl.kt:32)
    at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:99)
    at org.jetbrains.kotlin.backend.konan.KonanConfig$resolvedLibraries$2.invoke(KonanConfig.kt:29)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at org.jetbrains.kotlin.backend.konan.KonanConfig.getResolvedLibraries$backend_native_compiler(KonanConfig.kt)
    at org.jetbrains.kotlin.backend.konan.TopDownAnalyzerFacadeForKonan.analyzeFiles(TopDownAnalyzerFacadeForKonan.kt:43)
    at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1$1.invoke(ToplevelPhases.kt:41)
    at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1$1.invoke(ToplevelPhases.kt)
    at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
    at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1.invoke(ToplevelPhases.kt:40)
    at org.jetbrains.kotlin.backend.konan.ToplevelPhasesKt$frontendPhase$1.invoke(ToplevelPhases.kt)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:58)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$namedOpUnitPhase$1.invoke(PhaseBuilders.kt:56)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
    at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$then$1.invoke(PhaseBuilders.kt:14)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:91)
    at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:18)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:90)
    at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:73)
    at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:33)
    at org.jetbrains.kotlin.backend.konan.KonanDriverKt.runTopLevelPhases(KonanDriver.kt:30)
    at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:78)
    at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:35)
    at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
    at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
    at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
    at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:81)
    at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:49)
    at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:214)
    at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:206)
    at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:217)
    at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:208)
    at org.jetbrains.kotlin.konan.util.UtilKt.profileIf(Util.kt:39)
    at org.jetbrains.kotlin.konan.util.UtilKt.profile(Util.kt:33)
    at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:210)
    at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:296)
    at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:16)```

**Comment by russhwolf** [comment]
Updated in 0.3
